### ISSUE TITLE
Can I use sonar-javascript as a standalone tool?

### ISSUE THREAD

**Issue by valaxy** [SonarSource/sonar-javascript#539]
Deploy a sonar server and make sonar-javascript as a plugin of that which is too heavy for me.

Is there any hack I can do to extract the check logic from the source to make it as a standalone cli tool?

Thanks.

**Comment by vilchik-elena** [comment]
Try http://www.sonarlint.org/commandline. It works without server, but unfortunately you can't tune profile (set of rules) without connecting it to a server.
Moreover, there is server sonarqube.com ready to use for open-source projects. While there you can't change set of rules as well, this feature should be available soon.

**Comment by inverno** [comment]
@valaxy , Elena's answer is perfectly valid, but, just in case that you need to do something very custom, have a look [here](https://github.com/SonarSource/sonar-javascript/blob/master/javascript-checks-testkit/src/main/java/org/sonar/javascript/checks/verifier/BulkVerifier.java#L59) for an example of how to run the analyzer directly within a standalone main-like method.

**Comment by valaxy** [comment]
Thank you very much for the help!
