### ISSUE TITLE
ClassNotFoundExecption in CommaOperatorInSwitchCaseCheck

### ISSUE THREAD

**Issue by dgerhardt** [SonarSource/sonar-javascript#552]
**I want to report a bug.**<br>
SonarQube Scanner crashes with a ClassNotFoundException if a case clause consists of a function call and logical OR.

**SonarJS version:** 2.21 (build 4409)<br>
**SonarQube version:** 6.3<br>
**SonarLint version:** -<br>
**Gradle version:** 3.4.1<br>
**SonarQube Scanner for Gradle version:** 2.3<br>

**Rule key:** S3616 (CommaOperatorInSwitchCaseCheck)

**Reproducer** 
```
switch (true) {
  case true:                   // OK
  case true || false:          // OK
  case f(x):                   // OK
  case f(x) || x:              // Exception
    break;
}
```

**Logs**
```
$ gradle sonarqube
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://plugins.gradle.org/m2/org/sonarsource/scanner/gradle/sonarqube-gradle-plugin/2.3/sonarqube-gradle-plugin-2.3.pom
Download https://plugins.gradle.org/m2/org/sonarsource/scanner/gradle/sonarqube-gradle-plugin/2.3/sonarqube-gradle-plugin-2.3.jar
:sonarqube
[...]
* What went wrong:
Execution failed for task ':sonarqube'.
> org/sonar/api/internal/google/common/collect/ImmutableList
[...]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sonarqube'.
[...]
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/internal/google/common/collect/ImmutableList
        at org.sonar.javascript.checks.CommaOperatorInSwitchCaseCheck.orExpressionOperands(CommaOperatorInSwitchCaseCheck.java:101)
        at org.sonar.javascript.checks.CommaOperatorInSwitchCaseCheck.visitCaseClause(CommaOperatorInSwitchCaseCheck.java:49)
        at org.sonar.javascript.tree.impl.statement.CaseClauseTreeImpl.accept(CaseClauseTreeImpl.java:91)
[...]
Caused by: java.lang.ClassNotFoundException: org.sonar.api.internal.google.common.collect.ImmutableList
[...]
```

**Expected behavior**

Analysis should not crash with an Exception. Instead an issue for rule S3616 should be reported.

**Comment by vilchik-elena** [comment]
@dgerhardt Thanks for reporting, we will try to fix asap.

To fix we should replace [this line|https://github.com/SonarSource/sonar-javascript/blob/432ceb89f4b9266b30d038ab3159cf451d9cae6c/javascript-checks/src/main/java/org/sonar/javascript/checks/CommaOperatorInSwitchCaseCheck.java#L24] with `import com.google.common.collect.ImmutableList;`

**Comment by vilchik-elena** [comment]
[SONARJS-992](https://jira.sonarsource.com/browse/SONARJS-992)

**Comment by inverno** [comment]
Done and released!
