### ISSUE TITLE
Support Vue.js Single File Components

### ISSUE THREAD

**Issue by Daniel1989** [SonarSource/sonar-javascript#576]
**I want to request a feature.** 

Hi, is there any plan to support .vue file?

**Comment by inverno** [comment]
Hi @Daniel1989 ,
thanks for bringing this up, currently we are considering to parse the javascript code inside the .vue `<script>` tag so that we could analyse it like any other js code sitting in a .js file. What do you think?

**Comment by Daniel1989** [comment]
Hi @inverno ,
Thanks for your reply, I think your idea is great for me. Could I know when this feature will be available?

**Comment by Jiangmx** [comment]
It is great for us too

**Comment by inverno** [comment]
@Daniel1989 
We are considering this feature for next iteration. As soon as it enters an iteration you'll see it here.
Pull requests, of course, are always welcome :-)

**Comment by Daniel1989** [comment]
@inverno Great thanks！

**Comment by inverno** [comment]
Reopening this. We'll close it when implemented :)

**Comment by uharbachou** [comment]
WIll be better for support ES6 syntax(ts as next feature).

A lot of projects used *.vue extension. Thanks

**Comment by andirdju** [comment]
while this is in progress, I think we can use this guide as workaround,

https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns

externalize the js file from the vue file.

**Comment by vilchik-elena** [comment]
- [ ] add some vue files to Ruling IT

**Comment by pwang2** [comment]
@vilchik-elena , any update for the feature availability?

**Comment by inverno** [comment]
@pwang2 it's been completed and released in SonarJS 3.1, see the milestone : https://github.com/SonarSource/sonar-javascript/milestone/4?closed=1

**Comment by pwang2** [comment]
From the link in the repo description, I only see jsx support not vue. I have sonarjs 3.1.1 installed and even after setup suffixes, still is in my vue file is ingored. Did I miss anything here? Thanks!

**Comment by inverno** [comment]
@pwang2 indeed we did not add `.vue` to the supported frameworks list, but that's just text. The `.vue` suffix is pre-configured in 3.1.1 and I just analyzed https://github.com/vuejs-templates/webpack-simple (which contains a `.vue` file) without any extra configuration.
Mind to provide the log of the analysis, the configuration you are using and maybe a sample `.vue` file that is failing to be analyzed?

**Comment by pwang2** [comment]
I got error as below and I included `sonar.javascript.file.suffixes=.js,.vue` in sonar-project.properties file. 
Also, I am using sonar-scanner docker image, not sure if that could be the reason.
```
ERROR: Unable to parse file: /var/lib/jenkins/workspace/xx/src/components/Fields/EL_BOOLEAN.vue
ERROR: Parse error at line 1 column 1:

 1: <template>
    ^
 2: <v-checkbox :label="name" :input-value="displayValue" @change="toggle" hide-details></v-checkbox>
 3: </template>
 4: 
 5: <script>
 6: import { mapMutations } from 'vuex';
```

**Comment by inverno** [comment]
@pwang2 no problem, good to know that it works for you

**Comment by saberduck** [comment]
@kamontat no, we don't support them yet, you can follow issue https://github.com/SonarSource/sonar-css/issues/109

**Comment by saberduck** [comment]
@kamontat yes, it is supported. This debug message you are seeing is coming from the new parser, but it's not relevant for the analysis.
