### ISSUE TITLE
Rule: Classes should not be too complex

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-javascript#691]
[RSPEC-1311](https://jira.sonarsource.com/browse/RSPEC-1311)

**Comment by vilchik-elena** [comment]
rule is deprecated

**Comment by SmileYun** [comment]
why the reason?

**Comment by vilchik-elena** [comment]
@SmileYun 
> Because the Cyclomatic Complexity of a class or application largely corresponds to LoC, those metrics aren't helpful, and should be deprecated/hidden.
(from https://jira.sonarsource.com/browse/MMF-151)

**Comment by SmileYun** [comment]
@vilchik-elena  Thank you very mach!

**Comment by SmileYun** [comment]
@vilchik-elena  The other word, should i pay attention to rule "Methods should not be too complex"?

**Comment by vilchik-elena** [comment]
@SmileYun as you wish:) rule is available in SonarJS plugin (with key `javascript:FunctionComplexity`) but it's not activated by default
The recommended way is to use rule for cognitive complexity (with key `javascript:S3776`)

**Comment by SmileYun** [comment]
@vilchik-elena  Thanks a lot!
