### ISSUE TITLE
S3776 | Change cognitive complexity to not analyse AMD module factory functions themselves

### ISSUE THREAD

**Issue by rjgotten** [SonarSource/sonar-javascript#716]
**Rule key:** javascript:S3776

Factory functions used when `define`-ing AMD modules are falsely flagged for high cognitive complexity as soon as said functions contain "statements subject to structural increments".

It's perfectly natural for some conditionals to appear in e.g. initialization of some variables that are global to the module's scope. For instance: some variables may depend on test results for browser support of particular API features and feature a ternary operator.

Instead of a straightforward solution like:

```js
define([ "support-test" ], function( isSupported ) {
  var foo = isSupported() ? "bar" : "baz";

  // ...
});
```

to fullfill the crazy conditions for the cognitive complexity escape hatch, one needs to write a convoluted:

```js
define([ "support-test" ], function( isSupported ) {
  var foo = (function() { return isSupported() ? "bar" : "baz" }());

  // ...
});
```

-----

**Proposed solution**

For AMD modules there is a better signal than relying on the top level function not carrying any "statements subject to structural increments" and that is to simply always ignore the factory function argument to the `define` call.

**Comment by vilchik-elena** [comment]
@rjgotten thanks for your feedback. This case is indeed tricky and we wanted to have generic approach for all cases of functions-"containers".

I see a point in your suggestion, but what if you have a big logic, like this:
```
define([ "support-test" ], function( isSupported ) {
  if (cond) {
     // ..  complexity of 10 here
  } else {
     // .. complexity of 15 here
  }

  // ...
});
```
Then no issue will be triggered.

Our suggestion is the following: as soon as we detect AMD module function, we calculate its complexity ignoring nested functions' complexity. WDYT?

**Comment by rjgotten** [comment]
@vilchik-elena 
> Our suggestion is the following: as soon as we detect AMD module function, we calculate its complexity ignoring nested functions' complexity. WDYT?

That would probably also do the trick, yes.

**Comment by inverno** [comment]
@rjgotten the RC with the fix is available here, feel free to test it : https://github.com/SonarSource/sonar-javascript/releases/tag/3.2-RC1

**Comment by rjgotten** [comment]
@inverno 
Thank you. I will have to have my employer's systems administration department have a look-see to roll this out, but I hope to be able to take it for a spin soon.
