### ISSUE TITLE
Fix priority of flow function type

### ISSUE THREAD

**Issue by inverno** [SonarSource/sonar-javascript#778]
The current grammar defines the following relative priorities : flow_function_type < flow_union_type < flow_intersection_type < all_the_rest

This means that this `string | number => string` is parsed like this `(string | number) => string` instead of like this `string | (number => string)`.

The correct priorities should be : flow_union_type < flow_intersection_type < flow_function_type < all_the_rest

We have not yet fixed it because the return type of arrow functions should avoid parsing as an unparenthesized function type. The current (wrong) priorities allow for an easy solution by starting parsing the return type from flow_union_type thus excluding the flow_function_type

**Comment by vilchik-elena** [comment]
Fixed by #780
